[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https://maps.googleapis.com https://connect.facebook.net;
      connect-src 'self' https://*.myshopify.com https://hook.us2.make.com https://maps.googleapis.com;
      img-src 'self' data: https: blob:;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
      font-src 'self' https://fonts.gstatic.com;
      frame-src 'self' https://checkout.shopify.com https://*.myshopify.com;
      worker-src 'self' blob:;
    """